services:
  - type: web
    name: faktury-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn faktury.wsgi
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: faktury.settings
      - key: SECRET_KEY
        value: tvoje_silne_tajne_klucove_slovo
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: .onrender.com
